### ISSUE TITLE
Missing motif entities?

### ISSUE THREAD

**Issue by sibyl229** [WormBase/pseudoace#76]
It seems that some motif entity can't be found in the datomic database (ws260). 

[ws260 acedb has the (AAAA)n motif](http://staging.wormbase.org/resources/motif/(AAAA)n#02--10)

`[:find ?e :where [?e :motif/id "(AAAA)n"]]` gets no results.

**Comment by mgrbyte** [comment]
As discussed on our recent call, this is due to Motif objects that _only_ have populated attributes that link to   homology data.
The CSV report in wormbase directory in our S3 for WS260 shows the following counts for Motif:

ACeDB | datomic | Missing | Added | Identical
-- | -- | -- | -- | --
Motif | motif | 23416 | 0 | 69269

We decided on the call to de-prioritise development on widgets that link to homology data until we find a solution for integrating that data.

**Comment by mgrbyte** [comment]
This I believe has been solved; reason is entities in the database that have no other attributes other than ID are not converted by the migration process. Motif entities with just an ID (`Name` in ACeDB) and homology would be dropped. 

Please re-open if this is not the case.
