### ISSUE TITLE
pseudoace as a library

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/pseudoace#9]
@a8wright 
After more review of the original clojure code in the hinxton-curation repo (wb, colanade, trace),
I've identified that it in fact uses more than just the `pseudoace.utils` module, but
also uses:
 `pseudoace.ts_import`
 `psuedoace.import`

As discussed on our last hangout; It'd be good  to have one name which can be used for this repository _and_ the clojure package which it provides.

The name of the command line tool is not of any importance [1]

Since you've said you're not keen on "pseudoace" as a name, how about calling this "acedatomic"?

Proposal:
- Re-name this repository to "acedatomic" 
- The leiningen project will be caleld wormbase/acedatomic, and distributed on clojars so
  other projects that depend on the code can then include (e.g `[wormbase/acedatomic <version>]`.
- Change the namespace in the clojure code from pseudoace to acedatomic

[1] 
Since when invoking
 `lein run` the function pointed to by `:main` is executed by default.

Thus, currently:
 `lein run ace-to-dataomic`
is the same as:
 `lein run`

**Comment by adamjohnwright** [comment]
@mgrbyte I agree with your diagnosis of the situation. Feel free to change the name of the repo and the name space. It is interesting that so many other parts use the importer - not expected. Feel free to organize things so that the shared code is in one repository and included in to repositories as necessary. I will be working on datomic-to-catalyst code today. hopefully I don't run into similar complexity.

**Comment by dasmoth** [comment]
The curation tool depends on the importer because it supports submitting .ace-formatted patches.

**Comment by mgrbyte** [comment]
We decided to keep the current name `pseudoace` (thanks to @a8wright  for agreeing!)

**Comment by mgrbyte** [comment]
Closed by d486d686f8d4320dee31d1f86a70002a2b134eeb
